//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutrackSimple.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public int OwerId { get; set; }
    
        public virtual UserEntity User { get; set; }
    }
}
