//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutrackSimple.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionEntity
    {
        public PermissionEntity()
        {
            this.Users = new HashSet<UserEntity>();
        }
    
        public int Id { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<UserEntity> Users { get; set; }
    }
}
